### ISSUE TITLE
HTTP Status Code should return 401 instead of 200 when sending invalid credentials

### ISSUE THREAD

**Issue by dwzzzl** [TeaInside/Tea-Messenger-API#14]
Referring to https://tools.ietf.org/html/rfc7235#section-3.1

**Comment by ammarfaizi2** [comment]
Hello,

I am sorry for the delay, I was really busy for a few weeks ago. I have just added 401 HTTP response code for the invalid credential.

Ref https://github.com/TeaInside/Tea-Messenger-API/pull/15

Thank you for correction.

**Comment by ammarfaizi2** [comment]
@dwzzzl Since there is nothing to talk anymore related to this issue, I decided to close this issue, thank you.
