### ISSUE TITLE
Prevent duplicate email in registration

### ISSUE THREAD

**Issue by ammarfaizi2** [TeaInside/Tea-Messenger-API#4]
We need to prevent duplicate email and phone number in registration. There are some possibilities of email and phone number duplication. But, I will split the issue related to the phone number duplication into a new one soon.
## The first issue which we have to put on high priority is about email duplication:
1. Based on the alphabet case. For example, there are 3 emails that were used by the users to register
 ammarfaizi2@gmail.com
 Ammarfaizi2@gmail.com
 AmMarfaizi2@gmail.com
**Those emails should never be accepted as unique emails.**
2. Based on its similarity. For example:
 ammarfaizi2@gmail.com
 ammar.faizi@gmail.com
 am.ma.rfai+zi@gmail.com
 ammar+faizi@gmail.com
 ammar_faizi@gmail.com
**Those emails should never be accepted as unique emails.**

How can we fix this issue?
Any idea?

**Comment by ammarfaizi2** [comment]
I am working on this, will send you an update soon.

**Comment by ammarfaizi2** [comment]
I have resolved this issue https://github.com/TeaInside/Tea-Messenger-API/pull/6, will make the tests case for this one soon.

**Comment by codenoid** [comment]
yeah, `strtolower` is the solution
